### PR TITLE
Added option to also return headers

### PR DESCRIPTION
**Pull request by vionemc**
there is a return header option and also the test

### CODE REVIEW

**Comment by SteelPangolin** [comment]
Thanks for the PR. I'm reviewing it now.

**Comment by vionemc** [comment]
Pease ping me if the update is submitted to python. I'd use the updated version right away for my own app

**Comment by vionemc** [comment]
@SteelPangolin the update I made is not submitted to the python library. I can't upgrade it using `pip install`

Can you please submit it? Thanks

**Comment by SteelPangolin** [comment]
Thanks for your code and patience. I've merged your change with some modifications: squashed into a single commit, and with updated comments and extended tests.

https://github.com/SteelPangolin/genderize/commit/6b87ef8c031947f37eb1c51c8077b56b09ba8617

I'll push a new version to PyPI tonight.

**Pull request closed without merging**
